kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Chart.Name }}
  selector:
    app: {{ .Chart.Name }}